sudo: false
language: java
install: make install
test: make test
jdk:
  - oraclejdk8
deploy:
  - provider: heroku
  - secure: "ByiRe+Eec3eEYrtGrETYOawHPHk+oaaRaJAoZpydXSxZT6Py5py7ISxivV3hFjmKn+snd+H+dfeZHvNcVlw6C4fZXgzmcbr4DUD+snG52SLq7uJzgjj5NEzqnij6MfF8ZDqMBBvxfLtAQFPYQSk6f30KoWgelrSimI1Syx7/lCllTRkv+D3DmoREY30pQejj1SxdrUCILlJYT5Dk23Q3cbnnePLMSZAVvfk/XMUqF4M6r287iwcJ4JBxu41O3z3VJfifPlSqMv9anZsZKs8MIgEzGHEMMKQYotDDlP3uK0/2u6LmVJwZXiPabmr7h759t1gUGZYG7j6byrJr4iHJyov2zUO+EyTl/g87QcK9mauhU+Bi03G9/b3H92TggG3PchTMMiL/hDokgYjGkle8JHGGmQOIVR4WPtfXvoTJ8+ECfpx9Oq2OHApra9QkVQ7eh3M7DygbaJ/Mn5JdaUN9CG+MldSWOzKid4Ko99MzYJBoGkEwHV9VBXEx4IVYVI43O9WfQivanaxQ88WgCCBEDwKxxiP4QisFEGfTI7vUzK4aaPCn5rniszJeKYWLCi4SEHJCxzSljhs+/N0o962wGRIIbJ5cQp5kQ3KWEIVoaFg0Zu/1exTI24FeF/c0SE9aKNCe6cNwjIdwsTYJAHhkRLpOTVPQRiqR9NVQ5v+1dYo="
